name: Coffee Cart Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  running_the_project_with_github_actions:
    name: Running the Project with Github Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Install java and maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven   

      - name: Running the Project with Github Actions
        run: mvn clean test
        
      - name: List Surefire Reports 
        run: ls -l target/surefire-reports

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
