name: Coffee Cart 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coffee_cafe_project:
    name: Coffee Cart Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Install java and maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven   

      - name: Coffee cart project
        run: mvn clean compile test -DsuiteXmlFile='XMLFiles/Menu.xml'

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
